#!/usr/bin/env bash

# Execute the docs to make sure all code examples are in sync with the library code.

vendor/bin/uptodocs run docs/introduction.md --before=docs/before.php
vendor/bin/uptodocs run docs/recursion.md --before=docs/before.php
