#!/usr/bin/env bash

# Execute the docs to make sure all code examples are in sync with the library code.

hasFailed=0

vendor/bin/uptodocs run README.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/design_goals.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/functional_paradigms.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/installation.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/introduction.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/naming_conventions.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/order_matters.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/performance.md --before=docs/before.php --output-format=github || hasFailed=1
vendor/bin/uptodocs run docs/recursion.md --before=docs/before.php --output-format=github || hasFailed=1

exit $hasFailed
