name: Benchmark

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'

    # create baseline
    - uses: actions/checkout@v2
      with:
          ref: 'b6ef6065d490639aff0233b8f612bdda1a1c55e6' # todo change to "main"

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: create a perf baseline
      run: composer benchmark-baseline

    # compare against current commit
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: compare PR against a perf baseline
      run: composer benchmark-compare-baseline
