name: Benchmark

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: create perf comparison
      run: |
        # create baseline
        git checkout cc0808fd2ecd30a563bbe20e5d4e989d7071aa03
        composer install --prefer-dist --no-progress --no-suggest
        composer benchmark-baseline
        
        # cleanup
        rm composer.lock
        
        # compare against current commit
        git checkout ${{ github.event.pull_request.head.sha }}
        composer install --prefer-dist --no-progress --no-suggest
        comparison=$(composer benchmark-compare-baseline)

        # prepare multi line message
        comparison="${comparison//'%'/'%25'}"
        comparison="${comparison//$'\n'/'%0A'}"
        comparison="${comparison//$'\r'/'%0D'}"
        
        echo "::notice $comparison"
