name: Benchmark

on: [push, pull_request_target]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: create perf comparison
      id: perf-compare
      run: |
        echo ::group::trigger baseline-setup
        git checkout main
        composer install --prefer-dist --no-progress
        echo ::endgroup::
        composer benchmark-baseline
        
        # baseline-cleanup
        rm composer.lock
        
        # compare against current commit
        git checkout ${{ github.event.pull_request.head.sha }}
        echo ::group::trigger patch-setup
        composer install --prefer-dist --no-progress
        echo ::endgroup::
        comparison=$(composer benchmark-compare-baseline)

        # prepare multi line message
        comparison="${comparison//'%'/'%25'}"
        comparison="${comparison//$'\n'/'%0A'}"
        comparison="${comparison//$'\r'/'%0D'}"
        
        echo "::set-output name=comparison::$comparison"

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: running benchmarks...

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
            ```
            ${{ steps.perf-compare.outputs.comparison }}
            ```

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
            ```
            ${{ steps.perf-compare.outputs.comparison }}
            ```
