name: Benchmark

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - run: |
        # create baseline
        git checkout 0635aaeb5e85dfae1b628286f3f738e6e09ba1ed
        composer install --prefer-dist --no-progress --no-suggest
        composer benchmark-baseline
        # compare against current commit
        git checkout ${{ github.event.pull_request.head.sha }}
        composer install --prefer-dist --no-progress --no-suggest
        composer benchmark-compare-baseline
